version: '3.7'
services:
  api:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
  database:
    container_name: nest_db
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PORT}:5432'